"""把「碟中谍 Mission: Impossible」经典示例加入游戏 OFFLINE 精选电台曲库。
碟中谍是「短语模式」(display_phrase + hero_idx)，数据结构与普通单词歌不同，
直接复用后端 main.py 的 _MISSION_DEMO 定义，保证时间轴/特效一致。
音频用相对路径 songs/mission.mp3（已拷到 public/songs 与 dist/songs）。完全离线。
"""
import sys, json
sys.path.insert(0, "backend")
from pathlib import Path

from morse_api.main import _MISSION_DEMO

ROOT = Path("/Users/bytedance/Desktop/Hackathon/final0710")
radio_path = ROOT / "frontend/src/offlineRadio.js"

# 依据后端 _MISSION_DEMO 组装一条 offlineRadio 条目（短语模式全字段透传）
mission = dict(_MISSION_DEMO)
mission_track = {
    "word": mission["word"],                      # "MI"
    "sub": "经典电波暗号：M(−−) + I(··) 循环 8 次",
    "style_label": mission["style_label"],        # 碟中谍主题曲
    "morse_pretty": mission["morse_pretty"],      # −− / ··
    "display_phrase": mission["display_phrase"],  # Mission: Impossible（短语模式关键字段）
    "hook_key": "经典主题",
    "hook_bpm": 0,
    "letter_timeline": mission["letter_timeline"],# 含 hero_idx / dot_effect / dash_effect
    "intro_duration_ms": mission["intro_duration_ms"],
    "audio_url": "songs/mission.mp3",             # OFFLINE 相对路径
    "demo": True,
    "demo_caption": mission.get("demo_caption", ""),
    "intro_anim_delay_ms": mission.get("intro_anim_delay_ms", 6000),
}

txt = radio_path.read_text(encoding="utf-8")
start = txt.index("export const OFFLINE_RADIO = ") + len("export const OFFLINE_RADIO = ")
end = txt.rindex(";")
arr = json.loads(txt[start:end])

# 去掉已存在的碟中谍（word==MI）再插到最前（招牌 demo 排第一）
arr = [t for t in arr if t.get("word") != "MI"]
arr.insert(0, mission_track)

radio_path.write_text(
    "// This file is generated by gen_demo_songs.py.\n"
    "// It lets the offline Interactive Space bundle keep song files and timelines in sync.\n"
    "export const OFFLINE_RADIO = " + json.dumps(arr, ensure_ascii=False, indent=2) + ";\n",
    encoding="utf-8")

print(f"[radio] 碟中谍已插入曲库首位。当前曲目：{[t['word'] for t in arr]}")
print(f"[mission] display_phrase={mission_track['display_phrase']}")
print(f"[mission] 时间轴条目数={len(mission_track['letter_timeline'])} "
      f"intro_ms={mission_track['intro_duration_ms']} anim_delay={mission_track['intro_anim_delay_ms']}")
print(f"[mission] 首条: {mission_track['letter_timeline'][0]}")
print("[done]")
