"""把「STAR / 东方禅意·古筝」完整成品加入游戏离线曲库（不调 MiniMax）。
复用已有的 STAR AI 人声编曲轨(_music.mp3)本地重混，拿到对齐的 letter_timeline，
用新的「乐器→特效」映射（古筝→pluck）产出点划特效，转码音频到游戏 songs 目录，
并更新 frontend/src/offlineRadio.js（替换旧 STAR 条目）。完全离线。
"""
import sys, json, subprocess, shutil
sys.path.insert(0, "backend")

if shutil.which("ffmpeg") is None:
    import static_ffmpeg  # type: ignore
    static_ffmpeg.add_paths()
FFMPEG = shutil.which("ffmpeg") or "ffmpeg"

from dataclasses import replace
from pathlib import Path

from morse_api.config import load_config
from morse_api.styles import resolve as resolve_style
from morse_api.morse_codec import abbrev_to_morse
from morse_api.drum_synth import (
    render_morse_hook_with_timeline, render_morse_drumkit_with_timeline, effect_for_hook,
)
from morse_api.main import _mix_hook_across_track, ASSETS_DIR

WORD, STYLE_ID, SUB = "STAR", "oriental", "循着古筝的电波，寻你如寻星"
BASENAME = "sample_STAR_oriental_vocal"
ROOT = Path("/Users/bytedance/Desktop/Hackathon/final0710")

cfg = load_config()
style = resolve_style(STYLE_ID)
if style.bpm_hint:
    cfg = replace(cfg, bpm=int(style.bpm_hint))
target_bpm = int(style.bpm_hint) if style.bpm_hint else int(cfg.bpm)

morse = abbrev_to_morse(WORD)

# 1) 逐字母时间轴（相对 hook 起点）+ 新特效
dot_effect, dash_effect = effect_for_hook(style)
print(f"[effect] {STYLE_ID} 乐器={style.hook_timbre} 形态={style.hook_kind} → dot={dot_effect} dash={dash_effect}")

# intro 逐字母 intervals（与 _run_generate 一致，用 intro drums 的时间轴，仅取时间）
from morse_api.drum_synth import render_intro_drums_with_timeline
_iw, intro_ms, intervals = render_intro_drums_with_timeline(
    morse.morse_dot_dash, cfg, short_voice=style.drum_voices[0], long_voice=style.drum_voices[1])
letters = list(morse.abbrev_normalized)
letter_timeline = []
for i, iv in enumerate(intervals):
    letter_timeline.append({
        "letter": letters[i] if i < len(letters) else "",
        "morse": iv["morse"],
        "morse_pretty": iv["morse"].replace(".", "·").replace("-", "−"),
        "start_ms": iv["start_ms"], "end_ms": iv["end_ms"],
        "dot_effect": dot_effect, "dash_effect": dash_effect,
    })

# 2) 本地重混拿到 first_hook_start_ms（复用已有 music 轨，不调 API）
if style.hook_kind == "percussive":
    hook_wave, hook_notes, hook_ms = render_morse_drumkit_with_timeline(
        morse.morse_dot_dash, cfg, kit=style.drum_kit, drum_preset=style.drum_preset, bpm=target_bpm)
else:
    hook_wave, hook_notes, hook_ms = render_morse_hook_with_timeline(
        morse.morse_dot_dash, cfg, root=style.key_root, scale=style.key_scale,
        octave=style.hook_octave, timbre=style.hook_timbre, bpm=target_bpm)
music_bytes = (ASSETS_DIR / f"{BASENAME}_music.mp3").read_bytes()
mixed, meta, stems = _mix_hook_across_track(
    hook_wave, hook_notes, hook_ms, music_bytes,
    sample_rate=cfg.sample_rate, base_overlay_db=style.drum_overlay_db, target_bpm=target_bpm)
first = float(meta.get("first_hook_start_ms", 0.0) or 0.0)
print(f"[mix] first_hook_start_ms={first} bpm={meta.get('detected_bpm')} key={meta.get('detected_key')}")

# 用重混后的合并轨覆盖 assets 成品（保证游戏音频与时间轴一致）
(ASSETS_DIR / f"{BASENAME}.mp3").write_bytes(mixed)

# 时间轴平移到 hook 起点（与 _run_generate 一致）
timeline_for_audio = []
for iv in letter_timeline:
    it = dict(iv)
    it["start_ms"] = round(float(it["start_ms"]) + first, 1)
    it["end_ms"] = round(float(it["end_ms"]) + first, 1)
    timeline_for_audio.append(it)

# 3) 转码到游戏 songs 目录（mono 44.1k 96k 小体积）
raw = ASSETS_DIR / f"{BASENAME}.mp3"
targets = [
    ROOT / "interactive_space/morse_jukebox/songs/star.mp3",
    ROOT / "frontend/dist/songs/star.mp3",
]
for dst in targets:
    dst.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run([FFMPEG, "-y", "-i", str(raw), "-ac", "1", "-ar", "44100", "-b:a", "96k", str(dst)],
                   check=True, capture_output=True)
    print(f"[song] 写入 {dst} ({dst.stat().st_size//1024}KB)")

# 4) 更新 offlineRadio.js —— 替换 STAR 条目
radio_path = ROOT / "frontend/src/offlineRadio.js"
txt = radio_path.read_text(encoding="utf-8")
start = txt.index("export const OFFLINE_RADIO = ") + len("export const OFFLINE_RADIO = ")
end = txt.rindex(";")
arr = json.loads(txt[start:end])
new_star = {
    "word": WORD, "sub": SUB, "style_label": style.label,
    "morse_pretty": morse.morse_pretty,
    "hook_key": f"{style.key_root} {'小调五声' if 'minor' in style.key_scale else '大调五声'}",
    "hook_bpm": round(float(meta.get("detected_bpm") or target_bpm), 1),
    "letter_timeline": timeline_for_audio,
    "intro_duration_ms": int(round(intro_ms + first)),
    "audio_url": "songs/star.mp3", "demo": False, "intro_anim_delay_ms": 0,
}
replaced = False
for i, t in enumerate(arr):
    if t.get("word") == WORD:
        arr[i] = new_star; replaced = True; break
if not replaced:
    arr.append(new_star)
radio_path.write_text(
    "// This file is generated by gen_demo_songs.py.\n"
    "// It lets the offline Interactive Space bundle keep song files and timelines in sync.\n"
    "export const OFFLINE_RADIO = " + json.dumps(arr, ensure_ascii=False, indent=2) + ";\n",
    encoding="utf-8")
print(f"[radio] offlineRadio.js 已更新 STAR（{'替换' if replaced else '新增'}），特效 dot={dot_effect} dash={dash_effect}")
print(f"[radio] letter_timeline 首条: {timeline_for_audio[0] if timeline_for_audio else '空'}")
print("[done]")
