"""用 music-3.0 重新生成游戏默认曲库（带连贯延音的新音色），直接本地调 _run_generate，
不经 HTTP 后端（避免重启中断），生成后转码到游戏 songs 目录并更新 offlineRadio.js。
碟中谍(MI)是短语 demo，单独由 add_mission_to_game.py 维护，此脚本不动它。
"""
import sys, json, subprocess, shutil
sys.path.insert(0, "backend")
if shutil.which("ffmpeg") is None:
    import static_ffmpeg  # type: ignore
    static_ffmpeg.add_paths()
FFMPEG = shutil.which("ffmpeg") or "ffmpeg"

from pathlib import Path
from morse_api.main import _run_generate, ASSETS_DIR

ROOT = Path("/Users/bytedance/Desktop/Hackathon/final0710")

# (词, 风格id, 副标题) —— 游戏默认曲库。纯音乐 demo（with_vocals=False，游戏播放用）。
# STAR 用 oriental(古筝)，与之前确认一致；其余沿用原 demo 风格。
JOBS = [
    ("LOVE",  "healing",       "把说不出口的爱，敲成一段旋律"),
    ("HOME",  "folk_acoustic", "无论多远，心里都有回家的节拍"),
    ("STAR",  "oriental",      "循着古筝的电波，寻你如寻星"),
    ("DREAM", "cinematic",     "所有未完成的梦，都在这段电波里"),
]

song_dirs = [
    ROOT / "interactive_space/morse_jukebox/songs",
    ROOT / "frontend/public/songs",
    ROOT / "frontend/dist/songs",
]
for d in song_dirs:
    d.mkdir(parents=True, exist_ok=True)

radio_items = []
for word, style_id, sub in JOBS:
    print(f"\n===== 生成 {word} / {style_id} (music-3.0 纯音乐) =====", flush=True)
    def cb(stage, pct, _w=word):
        print(f"  [{pct:3d}%] {stage}", flush=True)
    try:
        res = _run_generate(word, style_id, with_vocals=False,
                            asset_basename=f"demo_{word.lower()}.mp3", progress_cb=cb)
    except Exception as e:  # noqa: BLE001
        print(f"  ❌ FAIL {word}: {type(e).__name__}: {e}", flush=True)
        continue
    raw = ASSETS_DIR / f"demo_{word.lower()}.mp3"
    # 转码 mono 44.1k 96k 到各 songs 目录（体积小，离线包友好）
    for d in song_dirs:
        dst = d / f"{word.lower()}.mp3"
        subprocess.run([FFMPEG, "-y", "-i", str(raw), "-ac", "1", "-ar", "44100", "-b:a", "96k", str(dst)],
                       check=True, capture_output=True)
    kb = (song_dirs[0] / f"{word.lower()}.mp3").stat().st_size // 1024
    radio_items.append({
        "word": word, "sub": sub, "style_label": res.get("style_label", style_id),
        "morse_pretty": res.get("morse_pretty", ""),
        "hook_key": res.get("hook_key", ""), "hook_bpm": res.get("hook_bpm", 0),
        "letter_timeline": res.get("letter_timeline", []),
        "intro_duration_ms": res.get("intro_duration_ms", 0),
        "audio_url": f"songs/{word.lower()}.mp3", "demo": False, "intro_anim_delay_ms": 0,
    })
    dot = res.get("letter_timeline", [{}])[0].get("dot_effect", "?")
    dash = res.get("letter_timeline", [{}])[0].get("dash_effect", "?")
    print(f"  ✅ {word} {kb}KB bpm={res.get('hook_bpm')} key={res.get('hook_key')} dot={dot} dash={dash}", flush=True)

# 更新 offlineRadio.js：保留碟中谍(MI)在首位，替换/追加这四首
radio_path = ROOT / "frontend/src/offlineRadio.js"
txt = radio_path.read_text(encoding="utf-8")
arr = json.loads(txt[txt.index("= ")+2:txt.rindex(";")])
mission = [t for t in arr if t.get("word") == "MI"]
new_words = {it["word"] for it in radio_items}
kept = [t for t in arr if t.get("word") not in new_words and t.get("word") != "MI"]
final_arr = mission + radio_items + kept
radio_path.write_text(
    "// This file is generated by gen_demo_songs.py.\n"
    "// It lets the offline Interactive Space bundle keep song files and timelines in sync.\n"
    "export const OFFLINE_RADIO = " + json.dumps(final_arr, ensure_ascii=False, indent=2) + ";\n",
    encoding="utf-8")
print(f"\n[radio] 曲库更新完成：{[t['word'] for t in final_arr]}")
print("[ALL DONE]")
