// This file is generated by gen_demo_songs.py.
// It lets the offline Interactive Space bundle keep song files and timelines in sync.
export const OFFLINE_RADIO = [
  {
    "word": "LOVE",
    "sub": "把说不出口的爱，敲成一段旋律",
    "style_label": "治愈钢琴",
    "morse_pretty": "·−·· −−− ···− ·",
    "hook_key": "C 大调五声",
    "hook_bpm": 112.3,
    "letter_timeline": [
      {
        "letter": "L",
        "morse": ".-..",
        "morse_pretty": "·−··",
        "start_ms": 900.0,
        "end_ms": 2149.9,
        "dot_effect": "bloom",
        "dash_effect": "pluck"
      },
      {
        "letter": "O",
        "morse": "---",
        "morse_pretty": "−−−",
        "start_ms": 2524.9,
        "end_ms": 4274.9,
        "dot_effect": "bloom",
        "dash_effect": "pluck"
      },
      {
        "letter": "V",
        "morse": "...-",
        "morse_pretty": "···−",
        "start_ms": 4649.9,
        "end_ms": 5899.8,
        "dot_effect": "bloom",
        "dash_effect": "pluck"
      },
      {
        "letter": "E",
        "morse": ".",
        "morse_pretty": "·",
        "start_ms": 6274.8,
        "end_ms": 6399.8,
        "dot_effect": "bloom",
        "dash_effect": "pluck"
      }
    ],
    "intro_duration_ms": 6900,
    "audio_url": "songs/love.mp3",
    "demo": false,
    "intro_anim_delay_ms": 0
  },
  {
    "word": "HOME",
    "sub": "无论多远，心里都有回家的节拍",
    "style_label": "民谣原声",
    "morse_pretty": "···· −−− −− ·",
    "hook_key": "A 小调五声",
    "hook_bpm": 80.7,
    "letter_timeline": [
      {
        "letter": "H",
        "morse": "....",
        "morse_pretty": "····",
        "start_ms": 900.0,
        "end_ms": 1950.0,
        "dot_effect": "crisp",
        "dash_effect": "pluck"
      },
      {
        "letter": "O",
        "morse": "---",
        "morse_pretty": "−−−",
        "start_ms": 2400.0,
        "end_ms": 4500.0,
        "dot_effect": "crisp",
        "dash_effect": "pluck"
      },
      {
        "letter": "M",
        "morse": "--",
        "morse_pretty": "−−",
        "start_ms": 4950.0,
        "end_ms": 6300.0,
        "dot_effect": "crisp",
        "dash_effect": "pluck"
      },
      {
        "letter": "E",
        "morse": ".",
        "morse_pretty": "·",
        "start_ms": 6749.9,
        "end_ms": 6899.9,
        "dot_effect": "crisp",
        "dash_effect": "pluck"
      }
    ],
    "intro_duration_ms": 8100,
    "audio_url": "songs/home.mp3",
    "demo": false,
    "intro_anim_delay_ms": 0
  },
  {
    "word": "STAR",
    "sub": "许一个愿，让它藏进星海的和弦",
    "style_label": "梦境迷幻",
    "morse_pretty": "··· − ·− ·−·",
    "hook_key": "A 大调五声",
    "hook_bpm": 76.0,
    "letter_timeline": [
      {
        "letter": "S",
        "morse": "...",
        "morse_pretty": "···",
        "start_ms": 900.0,
        "end_ms": 1665.3,
        "dot_effect": "bloom",
        "dash_effect": "hit"
      },
      {
        "letter": "T",
        "morse": "-",
        "morse_pretty": "−",
        "start_ms": 2124.5,
        "end_ms": 2736.7,
        "dot_effect": "bloom",
        "dash_effect": "hit"
      },
      {
        "letter": "A",
        "morse": ".-",
        "morse_pretty": "·−",
        "start_ms": 3195.9,
        "end_ms": 4114.3,
        "dot_effect": "bloom",
        "dash_effect": "hit"
      },
      {
        "letter": "R",
        "morse": ".-.",
        "morse_pretty": "·−·",
        "start_ms": 4573.5,
        "end_ms": 5798.0,
        "dot_effect": "bloom",
        "dash_effect": "hit"
      }
    ],
    "intro_duration_ms": 5798,
    "audio_url": "songs/star.mp3",
    "demo": false,
    "intro_anim_delay_ms": 0
  },
  {
    "word": "DREAM",
    "sub": "所有未完成的梦，都在这段电波里",
    "style_label": "电影叙事",
    "morse_pretty": "−·· ·−· · ·− −−",
    "hook_key": "D 小调",
    "hook_bpm": 152.0,
    "letter_timeline": [
      {
        "letter": "D",
        "morse": "-..",
        "morse_pretty": "−··",
        "start_ms": 900.0,
        "end_ms": 1900.0,
        "dot_effect": "hit",
        "dash_effect": "hit"
      },
      {
        "letter": "R",
        "morse": ".-.",
        "morse_pretty": "·−·",
        "start_ms": 2274.9,
        "end_ms": 3274.9,
        "dot_effect": "hit",
        "dash_effect": "hit"
      },
      {
        "letter": "E",
        "morse": ".",
        "morse_pretty": "·",
        "start_ms": 3649.9,
        "end_ms": 3774.9,
        "dot_effect": "hit",
        "dash_effect": "hit"
      },
      {
        "letter": "A",
        "morse": ".-",
        "morse_pretty": "·−",
        "start_ms": 4149.9,
        "end_ms": 4899.8,
        "dot_effect": "hit",
        "dash_effect": "hit"
      },
      {
        "letter": "M",
        "morse": "--",
        "morse_pretty": "−−",
        "start_ms": 5274.8,
        "end_ms": 6399.8,
        "dot_effect": "hit",
        "dash_effect": "hit"
      }
    ],
    "intro_duration_ms": 6900,
    "audio_url": "songs/dream.mp3",
    "demo": false,
    "intro_anim_delay_ms": 0
  }
];
